spring.application.name=order-api-foundation
spring.datasource.url=jdbc:postgresql://localhost:5433/order_api_foundation
spring.datasource.username=order_user
spring.datasource.password=order_password

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
